/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bchat.gui;

import bchat.controllers.GroupController;
import bchat.controllers.UserGroupController;
import bchat.entities.GroupImp;
import java.rmi.RemoteException;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author Blacky
 */
public class GroupMenuFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form LoginFrame
     */
    private final int groupId;
    private boolean isAdmin = true;

    public GroupMenuFrame(int groupId) {
        initComponents();
        this.groupId = groupId;

        MainUser.desk2.add(this);
        this.setLocation(0, 0);

        // remove the north pane of this frame
        BasicInternalFrameUI bi = (BasicInternalFrameUI) this.getUI();
        bi.setNorthPane(null);
        setLocation(0, 0);

        // hide addUser/deleteUser buttons if current user is not admin
        GroupImp group = GroupController.INSTANCE.findById(groupId);
        if (group.getAdminId() != MainUser.user.getIduser()) {
            // not admin
            addUser.setVisible(false);
            deleteUser.setVisible(false);
            addLabel.setVisible(false);
            deleteLabel.setVisible(false);
            isAdmin = false;
        }

        this.requestFocus();
        this.requestFocusInWindow();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        viewAddMembers = new javax.swing.JLabel();
        okBtn = new javax.swing.JButton();
        addUser = new javax.swing.JButton();
        deleteUser = new javax.swing.JButton();
        clearChatBtn = new javax.swing.JButton();
        leaveGroupBtn = new javax.swing.JButton();
        viewGroupUsers = new javax.swing.JButton();
        clearLabel = new javax.swing.JLabel();
        addLabel = new javax.swing.JLabel();
        deleteLabel = new javax.swing.JLabel();
        exitLabel = new javax.swing.JLabel();
        viewLabel = new javax.swing.JLabel();

        setBorder(null);
        setEnabled(false);

        jPanel1.setBackground(new java.awt.Color(5, 100, 153));
        jPanel1.setPreferredSize(new java.awt.Dimension(220, 410));

        viewAddMembers.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        viewAddMembers.setForeground(new java.awt.Color(255, 255, 255));
        viewAddMembers.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        viewAddMembers.setText("Group Menu");
        viewAddMembers.setToolTipText("");

        okBtn.setBackground(new java.awt.Color(5, 100, 153));
        okBtn.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        okBtn.setForeground(new java.awt.Color(255, 255, 255));
        okBtn.setText("OK");
        okBtn.setBorder(null);
        okBtn.setContentAreaFilled(false);
        okBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okBtnActionPerformed(evt);
            }
        });

        addUser.setBackground(new java.awt.Color(8, 151, 230));
        addUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bchat/res/addUser.png"))); // NOI18N
        addUser.setToolTipText("");
        addUser.setBorder(null);
        addUser.setBorderPainted(false);
        addUser.setContentAreaFilled(false);
        addUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUserActionPerformed(evt);
            }
        });

        deleteUser.setBackground(new java.awt.Color(8, 151, 230));
        deleteUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bchat/res/deleteUser2.png"))); // NOI18N
        deleteUser.setToolTipText("");
        deleteUser.setBorder(null);
        deleteUser.setBorderPainted(false);
        deleteUser.setContentAreaFilled(false);
        deleteUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteUserActionPerformed(evt);
            }
        });

        clearChatBtn.setBackground(new java.awt.Color(8, 151, 230));
        clearChatBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bchat/res/clear.png"))); // NOI18N
        clearChatBtn.setToolTipText("");
        clearChatBtn.setBorder(null);
        clearChatBtn.setBorderPainted(false);
        clearChatBtn.setContentAreaFilled(false);
        clearChatBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearChatBtnActionPerformed(evt);
            }
        });

        leaveGroupBtn.setBackground(new java.awt.Color(8, 151, 230));
        leaveGroupBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bchat/res/leave_grp.png"))); // NOI18N
        leaveGroupBtn.setToolTipText("");
        leaveGroupBtn.setBorder(null);
        leaveGroupBtn.setBorderPainted(false);
        leaveGroupBtn.setContentAreaFilled(false);
        leaveGroupBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leaveGroupBtnActionPerformed(evt);
            }
        });

        viewGroupUsers.setBackground(new java.awt.Color(8, 151, 230));
        viewGroupUsers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bchat/res/lname.png"))); // NOI18N
        viewGroupUsers.setToolTipText("");
        viewGroupUsers.setBorder(null);
        viewGroupUsers.setBorderPainted(false);
        viewGroupUsers.setContentAreaFilled(false);
        viewGroupUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewGroupUsersActionPerformed(evt);
            }
        });

        clearLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        clearLabel.setForeground(new java.awt.Color(255, 255, 255));
        clearLabel.setText("Clear Chat");

        addLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addLabel.setForeground(new java.awt.Color(255, 255, 255));
        addLabel.setText("Add a Member");

        deleteLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        deleteLabel.setForeground(new java.awt.Color(255, 255, 255));
        deleteLabel.setText("Remove a Member");

        exitLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        exitLabel.setForeground(new java.awt.Color(255, 255, 255));
        exitLabel.setText("Leave Group");

        viewLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        viewLabel.setForeground(new java.awt.Color(255, 255, 255));
        viewLabel.setText("View Members");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(leaveGroupBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(exitLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(deleteUser, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(deleteLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(addUser, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(addLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(clearChatBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(clearLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(viewAddMembers, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(viewGroupUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(viewLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(okBtn)))
                .addGap(15, 15, 15))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(viewAddMembers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(viewGroupUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(clearChatBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(clearLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addComponent(addUser, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(addLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(deleteUser, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(deleteLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(leaveGroupBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(exitLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(okBtn)
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okBtnActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_okBtnActionPerformed

    private void addUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUserActionPerformed
        AddUserToGroupFrame frame = new AddUserToGroupFrame(groupId);
        MainUser.desk2.add(frame);
        frame.setLocation(317, 0);
        frame.setVisible(true);
    }//GEN-LAST:event_addUserActionPerformed

    private void deleteUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteUserActionPerformed
        RemoveUserFromGroupFrame frame = new RemoveUserFromGroupFrame(groupId);
        MainUser.desk2.add(frame);
        frame.setLocation(317, 0);
        frame.setVisible(true);
    }//GEN-LAST:event_deleteUserActionPerformed

    private void clearChatBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearChatBtnActionPerformed
        String message = "<html><b>Are you sure you want to clear all chat?</b></html>";
        int choice = JOptionPane.showConfirmDialog(this,
                message,
                "Confirm Clear Action",
                JOptionPane.YES_NO_OPTION);

        switch (choice) {
            case JOptionPane.YES_OPTION:
                MainUser.groupChatFrames.get(groupId).chatArea.setText("");
                break;

            case JOptionPane.NO_OPTION:
                break;

            default:
                break;
        }
    }//GEN-LAST:event_clearChatBtnActionPerformed

    private void leaveGroupBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leaveGroupBtnActionPerformed
        String message = "<html><b>Are you sure you want to leave the group?</b></html>";
        if (isAdmin) {
            message += "\n<html><b>The group will be deleted with all its members.</b></html>";
        }

        int choice = JOptionPane.showConfirmDialog(this,
                message,
                "Confirm Leave Action",
                JOptionPane.YES_NO_OPTION);

        try {
            switch (choice) {
                case JOptionPane.YES_OPTION:
                    // get the frame of group
                    GroupChatFrame tmpFrame = MainUser.groupChatFrames.get(groupId);

                    // remove group from jlist
                    MainUser.allGroupsFrame.removeFromJList(groupId);

                    // update hashmap of userGroups (locally)
                    MainUser.userGroups.remove(groupId);

                    if (isAdmin) {
                        // send notice to all group members
                        String noticeMessage = " *** Group deleted by Admin ***\n";
                        String noticeIdComb = groupId + "-" + MainUser.user.getIduser();
                        MainUser.proxy.sendToGroup(noticeMessage, noticeIdComb);

                        // remove group for all users (server)
                        for (int userId : MainUser.proxy.getGroupUsersIDs(groupId)) {
                            String idComb = groupId + "-" + userId;
                            MainUser.proxy.deleteGroup(idComb);
                        }

                        // delete group (db)
                        GroupController.INSTANCE.delete(groupId);

                        tmpFrame.chatArea.append(" *** You deleted the group ***\n");

                    } else {
                        // not admin
                        String noticeMessage = " *** " + MainUser.user.getFirstName() + " " + MainUser.user.getLastName() + " left the group ***";
                        String noticeIdComb = groupId + "-" + MainUser.user.getIduser();
                        MainUser.proxy.sendToGroup(noticeMessage, noticeIdComb);

                        // remove user from group (server)
                        String idComb = groupId + "-" + MainUser.user.getIduser();
                        MainUser.proxy.deleteGroup(idComb);

                        // remove user from group (db)
                        UserGroupController.INSTANCE.removeUserFromGroup(MainUser.user.getIduser(), groupId);

                        tmpFrame.chatArea.append(" *** You left the group ***\n");
                    }

                    this.setVisible(false);
                    tmpFrame.setVisible(false);
                    MainUser.desk2.remove(this);
                    MainUser.desk2.remove(tmpFrame);

                    break;

                case JOptionPane.NO_OPTION:
                    break;

                default:
                    break;
            }
        } catch (RemoteException | SQLException ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_leaveGroupBtnActionPerformed

    private void viewGroupUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewGroupUsersActionPerformed
        ViewGroupUsersFrame frame = new ViewGroupUsersFrame(groupId);
        MainUser.desk2.add(frame);
        frame.setLocation(317, 0);
        frame.setVisible(true);
    }//GEN-LAST:event_viewGroupUsersActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addLabel;
    public javax.swing.JButton addUser;
    private javax.swing.JButton clearChatBtn;
    private javax.swing.JLabel clearLabel;
    private javax.swing.JLabel deleteLabel;
    public javax.swing.JButton deleteUser;
    private javax.swing.JLabel exitLabel;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JButton leaveGroupBtn;
    private javax.swing.JButton okBtn;
    private javax.swing.JLabel viewAddMembers;
    private javax.swing.JButton viewGroupUsers;
    private javax.swing.JLabel viewLabel;
    // End of variables declaration//GEN-END:variables
}
