/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bchat.gui;

import bchat.controllers.GroupController;
import bchat.controllers.UserController;
import bchat.controllers.UserGroupController;
import bchat.utilities.MyColors;
import java.awt.Color;
import java.rmi.RemoteException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author Blacky
 */
public class SettingFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form LoginFrame
     */
    public SettingFrame() {
        initComponents();

        // remove the north pane of this frame
        BasicInternalFrameUI bi = (BasicInternalFrameUI) this.getUI();
        bi.setNorthPane(null);
        setLocation(-10, 0);

        // change the color of jOptionPane
        UIManager.put("OptionPane.background", new Color(5, 100, 153));
        UIManager.getLookAndFeelDefaults().put("Panel.background", new Color(5, 100, 153));
        UIManager.put("control", new Color(5, 100, 153));
        UIManager.put("OptionPane.messageForeground", Color.WHITE);

        editUsername.setVisible(false);
        editPass.setVisible(false);

        this.requestFocusInWindow();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        username = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        fullName = new javax.swing.JTextField();
        checkbox1 = new java.awt.Checkbox();
        editUsername = new javax.swing.JButton();
        deleteAccount = new javax.swing.JButton();
        editPass = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setBorder(null);
        setEnabled(false);

        jPanel1.setBackground(new java.awt.Color(5, 100, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Settings");

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bchat/res/username.png"))); // NOI18N
        jLabel2.setToolTipText("");

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bchat/res/password.png"))); // NOI18N
        jLabel3.setToolTipText("");

        password.setBackground(new java.awt.Color(255, 255, 255));
        password.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        password.setForeground(new java.awt.Color(51, 153, 255));
        password.setToolTipText("");
        password.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        password.setDisabledTextColor(new java.awt.Color(8, 151, 230));
        password.setPreferredSize(new java.awt.Dimension(60, 20));
        password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordFocusLost(evt);
            }
        });

        username.setBackground(new java.awt.Color(255, 255, 255));
        username.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        username.setForeground(new java.awt.Color(8, 151, 230));
        username.setToolTipText("");
        username.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        username.setDisabledTextColor(new java.awt.Color(8, 151, 230));
        username.setPreferredSize(new java.awt.Dimension(60, 20));
        username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                usernameFocusLost(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bchat/res/fname.png"))); // NOI18N
        jLabel4.setToolTipText("");

        fullName.setEditable(false);
        fullName.setBackground(new java.awt.Color(255, 255, 255));
        fullName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        fullName.setForeground(new java.awt.Color(8, 151, 230));
        fullName.setToolTipText("");
        fullName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        fullName.setDisabledTextColor(new java.awt.Color(8, 151, 230));

        checkbox1.setLabel("checkbox1");
        checkbox1.setVisible(false);

        editUsername.setBackground(new java.awt.Color(8, 151, 230));
        editUsername.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bchat/res/edit.png"))); // NOI18N
        editUsername.setToolTipText("");
        editUsername.setBorder(null);
        editUsername.setBorderPainted(false);
        editUsername.setContentAreaFilled(false);
        editUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editUsernameActionPerformed(evt);
            }
        });

        deleteAccount.setBackground(new java.awt.Color(8, 151, 230));
        deleteAccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bchat/res/trash_can.png"))); // NOI18N
        deleteAccount.setToolTipText("Delete Account");
        deleteAccount.setBorder(null);
        deleteAccount.setBorderPainted(false);
        deleteAccount.setContentAreaFilled(false);
        deleteAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteAccountActionPerformed(evt);
            }
        });

        editPass.setBackground(new java.awt.Color(8, 151, 230));
        editPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bchat/res/edit.png"))); // NOI18N
        editPass.setToolTipText("");
        editPass.setBorder(null);
        editPass.setBorderPainted(false);
        editPass.setContentAreaFilled(false);
        editPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editPassActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Delete Account");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(checkbox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(deleteAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(editUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(fullName, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(editPass, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel1)))
                .addGap(0, 30, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel1)
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fullName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(checkbox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editPass, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(editUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deleteAccount, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameFocusGained
        editUsername.setVisible(true);
    }//GEN-LAST:event_usernameFocusGained

    private void usernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameFocusLost
        editUsername.setVisible(false);
    }//GEN-LAST:event_usernameFocusLost

    private void passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFocusGained
        editPass.setVisible(true);
    }//GEN-LAST:event_passwordFocusGained

    private void passwordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFocusLost
        editPass.setVisible(false);
    }//GEN-LAST:event_passwordFocusLost

    private void editPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editPassActionPerformed
        String newPass = password.getText();
        if (newPass.equals(MainUser.user.getPassword())) {
            JOptionPane.showMessageDialog(this,
                    "<html><b>Nothing to change</b></html>",
                    "Entry Alert",
                    JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        int choice = JOptionPane.showConfirmDialog(this,
                "<html><b>Change password?</b></html>",
                "Confirm Edit Action",
                JOptionPane.YES_NO_OPTION);

        switch (choice) {
            case JOptionPane.YES_OPTION:
                try {
                    UserController.INSTANCE.update(MainUser.user.getUsername(), newPass, MainUser.user.getIduser());
                    MainUser.user.setPassword(newPass);
                    JOptionPane.showMessageDialog(this,
                            "<html><b>Password changed successfully!</b></html>",
                            "Success",
                            JOptionPane.INFORMATION_MESSAGE);
                } catch (SQLException ex) {
                    System.out.println(ex.getMessage());
                }
                break;

            case JOptionPane.NO_OPTION:
                password.setText(MainUser.user.getPassword());
                break;

            default:
                break;
        }
    }//GEN-LAST:event_editPassActionPerformed

    private void editUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editUsernameActionPerformed
        String newUsername = username.getText();
        if (newUsername.equals(MainUser.user.getUsername())) {
            JOptionPane.showMessageDialog(this,
                    "<html><b>Nothing to change</b></html>",
                    "Entry Alert",
                    JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        int choice = JOptionPane.showConfirmDialog(this,
                "<html><b>Change username?</b></html>",
                "Confirm Edit Action",
                JOptionPane.YES_NO_OPTION);

        switch (choice) {
            case JOptionPane.YES_OPTION: {
                try {
                    UserController.INSTANCE.update(newUsername, MainUser.user.getPassword(), MainUser.user.getIduser());
                    MainUser.user.setUsername(newUsername);
                    JOptionPane.showMessageDialog(this,
                            "<html><b>Username changed successfully!</b></html>",
                            "Success",
                            JOptionPane.INFORMATION_MESSAGE);
                } catch (SQLException ex) {
                    System.out.println(ex.getMessage());
                }
            }
            break;

            case JOptionPane.NO_OPTION:
                username.setText(MainUser.user.getUsername());
                break;

            default:
                break;
        }
    }//GEN-LAST:event_editUsernameActionPerformed

    private void deleteAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteAccountActionPerformed
        String pass = JOptionPane.showInputDialog(this,
                "<html><b>Enter your password to continue</b></html>",
                "Success",
                JOptionPane.INFORMATION_MESSAGE);

        if (!pass.equals(MainUser.user.getPassword())) {
            JOptionPane.showMessageDialog(this,
                    "<html><b>Wrong Password</b></html>",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        int choice = JOptionPane.showConfirmDialog(this,
                "<html><b>Permanently delete account?</b></html>",
                "Confirm Delete Action",
                JOptionPane.YES_NO_OPTION);

        switch (choice) {
            case JOptionPane.YES_OPTION:
                try {
                    // disconnecting user
                    MainUser.proxy.disconnect(MainUser.user.getIduser());

                    MainUser.loggedIN = false;

                    // adjust the view
                    MainUser.chatBtn.setVisible(false);

                    MainUser.groupBtn.setBackground(MyColors.LIGHT_BLUE);
                    MainUser.groupBtn.setVisible(false);

                    MainUser.broadcastBtn.setBackground(MyColors.LIGHT_BLUE);
                    MainUser.broadcastBtn.setVisible(false);

                    MainUser.settingBtn.setBackground(MyColors.LIGHT_BLUE);
                    MainUser.settingBtn.setVisible(false);

                    MainUser.logoutBtn.setVisible(false);
                    MainUser.homeBtn.setVisible(true);

                    // delete old userChatFrames
                    MainUser.userChatFrames.values().forEach((frame) -> {
                        frame.dispose();
                    });

                    // delete old groupChatFrames
                    MainUser.groupChatFrames.values().forEach((frame) -> {
                        frame.dispose();
                    });

                    MainUser.userChatFrames.clear();
                    MainUser.groupChatFrames.clear();
                    MainUser.desk2.removeAll();

                    // clear display frames
                    MainUser.allUsersFrame.clearJList();
                    MainUser.allGroupsFrame.clearJList();

                    MainUser.loginFrame.setVisible(true);

                    // delete user groups from server
                    for (int groupId : MainUser.userGroups.keySet()) {
                        int adminId = GroupController.INSTANCE.findById(groupId).getAdminId();
                        if (adminId == MainUser.user.getIduser()) {
                            // user is group admin -> delete group for all
                            // send notice to all group members
                            String noticeMessage = " *** Group deleted by Admin ***\n";
                            String noticeIdComb = groupId + "-" + MainUser.user.getIduser();
                            MainUser.proxy.sendToGroup(noticeMessage, noticeIdComb);

                            // remove group for all users (server)
                            for (int userId : MainUser.proxy.getGroupUsersIDs(groupId)) {
                                String idComb = groupId + "-" + userId;
                                MainUser.proxy.deleteGroup(idComb);
                            }

                            // delete group (db)
                            GroupController.INSTANCE.delete(groupId);
                        } else {
                            // not admin -> leave group
                            String noticeMessage = " *** " + MainUser.user.getFirstName() + " " + MainUser.user.getLastName() + " left the group ***";
                            String noticeIdComb = groupId + "-" + MainUser.user.getIduser();
                            MainUser.proxy.sendToGroup(noticeMessage, noticeIdComb);

                            // remove user from group (server)
                            String idComb = groupId + "-" + MainUser.user.getIduser();
                            MainUser.proxy.deleteGroup(idComb);

                            // remove user from group (db)
                            UserGroupController.INSTANCE.removeUserFromGroup(MainUser.user.getIduser(), groupId);
                        }
                    }

                    // clear user groups locally 
                    MainUser.userGroups.clear();

                    // delete user from db
                    UserController.INSTANCE.delete(MainUser.user.getIduser());
//                    UserGroupController.INSTANCE.removeUserGroups(MainUser.user.getIduser());

                    this.setTitle("BChat - Login");

                    JOptionPane.showMessageDialog(this,
                            "<html><b>Account deleted successfully</b></html>",
                            "Success",
                            JOptionPane.ERROR_MESSAGE);

                } catch (RemoteException | SQLException ex) {
                    System.out.println(ex.getMessage());
                }

                break;

            case JOptionPane.NO_OPTION:
                break;

            default:
                break;
        }
    }//GEN-LAST:event_deleteAccountActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Checkbox checkbox1;
    private javax.swing.JButton deleteAccount;
    private javax.swing.JButton editPass;
    private javax.swing.JButton editUsername;
    public javax.swing.JTextField fullName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JPasswordField password;
    public javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
