/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bchat.gui;

import bchat.utilities.MyColors;
import java.awt.BorderLayout;
import java.awt.Color;
import java.rmi.RemoteException;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JToolBar;
import javax.swing.UIManager;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author Blacky
 */
public class UserChatFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form LoginFrame
     */
    private final int remoteUserId;
    public final UserMenuFrame userMenuFrame;
    
    public UserChatFrame(int remoteUserId) {
        initComponents();

        this.remoteUserId = remoteUserId;
        this.userMenuFrame = new UserMenuFrame(remoteUserId);
        this.userMenuFrame.setLocation(317, 0);
        
        // remove the north pane of this frame
        BasicInternalFrameUI bi = (BasicInternalFrameUI) this.getUI();
        bi.setNorthPane(null);
        setLocation(-10, 0);

        // disable horizental scrolling
        chatArea.setLineWrap(true);
        chatArea.setWrapStyleWord(true);
        
        // change the color of jOptionPane
        UIManager.put("OptionPane.background", new Color(5, 100, 153));
        UIManager.getLookAndFeelDefaults().put("Panel.background", new Color(5, 100, 153));
        UIManager.put("control", new Color(5, 100, 153));
        UIManager.put("OptionPane.messageForeground", Color.WHITE);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        remoteName = new javax.swing.JLabel();
        profile = new javax.swing.JLabel();
        groupMenuBtn = new javax.swing.JButton();
        SRFile = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        chatArea = new javax.swing.JTextArea();
        messageText = new javax.swing.JTextField();
        sendMessageBtn = new javax.swing.JButton();

        setBorder(null);
        setEnabled(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel5.setBackground(new java.awt.Color(8, 151, 230));

        remoteName.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        remoteName.setForeground(new java.awt.Color(255, 255, 255));
        remoteName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        profile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bchat/res/user.png"))); // NOI18N

        groupMenuBtn.setBackground(new java.awt.Color(8, 151, 230));
        groupMenuBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bchat/res/menu_bars.png"))); // NOI18N
        groupMenuBtn.setToolTipText("Menu");
        groupMenuBtn.setBorder(null);
        groupMenuBtn.setBorderPainted(false);
        groupMenuBtn.setContentAreaFilled(false);
        groupMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                groupMenuBtnActionPerformed(evt);
            }
        });

        SRFile.setText("File");
        SRFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SRFileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(profile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(remoteName, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SRFile)
                .addGap(81, 81, 81)
                .addComponent(groupMenuBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(SRFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(remoteName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(profile, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(groupMenuBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        chatArea.setEditable(false);
        chatArea.setColumns(20);
        chatArea.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        chatArea.setForeground(new java.awt.Color(5, 100, 153));
        chatArea.setRows(5);
        jScrollPane1.setViewportView(chatArea);

        messageText.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        messageText.setForeground(new java.awt.Color(204, 204, 204));
        messageText.setText(" Type a message");
        messageText.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        messageText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                messageTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                messageTextFocusLost(evt);
            }
        });

        sendMessageBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bchat/res/send.png"))); // NOI18N
        sendMessageBtn.setToolTipText("Send Message");
        sendMessageBtn.setAlignmentY(0.0F);
        sendMessageBtn.setBorder(null);
        sendMessageBtn.setContentAreaFilled(false);
        sendMessageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendMessageBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(messageText, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sendMessageBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(messageText, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sendMessageBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sendMessageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendMessageBtnActionPerformed
        String message = messageText.getText();

        if (message == null || message.equals(" ") || message.equals(" Type a message")) {
            return;
        }

        // send the message with the user's name
        String sendMessage = " " + MainUser.user.getFirstName() + ": " + message;
        try {
            MainUser.proxy.send(sendMessage, remoteUserId, MainUser.user.getIduser()); 
            chatArea.append(" You: " + message + "\n");

        } catch (RemoteException ex) {
            System.out.println(ex.getMessage());
        }

        messageText.setForeground(MyColors.GRAY);
        messageText.setText(" Type a message");
    }//GEN-LAST:event_sendMessageBtnActionPerformed

    private void messageTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_messageTextFocusGained
        if (messageText.getText().equals(" Type a message")) {
            messageText.setText(" ");
            messageText.setForeground(MyColors.LIGHT_BLUE);
        }
    }//GEN-LAST:event_messageTextFocusGained

    private void messageTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_messageTextFocusLost
        if (messageText.getText().equals(" ")) {
            messageText.setText(" Type a message");
            messageText.setForeground(MyColors.GRAY);
        }
    }//GEN-LAST:event_messageTextFocusLost

    private void groupMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_groupMenuBtnActionPerformed
        userMenuFrame.setVisible(true);
        MainUser.desk2.moveToFront(userMenuFrame);
    }//GEN-LAST:event_groupMenuBtnActionPerformed

    private void SRFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SRFileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SRFileActionPerformed




    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SRFile;
    public javax.swing.JTextArea chatArea;
    private javax.swing.JButton groupMenuBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextField messageText;
    public javax.swing.JLabel profile;
    public javax.swing.JLabel remoteName;
    public javax.swing.JButton sendMessageBtn;
    // End of variables declaration//GEN-END:variables
}
